name: 'CD: Cloudformation Policy Check'
on:
  pull-request

jobs:
  cfn-lint:
    runs-on: ubuntu-latest
    name: 'CloudFormation Linting...'
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2
      - name: Run the Linter
        run: |
          cfn-lint -t cloudformation/cfn-lint-examples/service.yaml -f pretty -i E3002,E3012,W
      - name: CFN Nagging
        uses: stelligent/cfn_nag@master
        with:
          input_path: cloudformation/cfn-nag-examples
          extra_args: --template-pattern '*.yaml' --ignore-fatal --output-format colortxt
      - name: Setup CFN Guard
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/aws-cloudformation/cloudformation-guard/main/install-guard.sh | sh
      - name: Poilcy check with CFN Guard
        run: | 
          export PATH=$PATH:~/.guard/bin && cfn-guard validate -d cloudformation/cfn-guard-examples/deployment-safety/service.yaml -r cloudformation/cfn-guard-examples/deployment-safety/ecs-taskdef.guard